### PR TITLE
Browser independent UI elements implemented

### LINKED ISSUE #2: Browser independent UI elements
The current UI elements at the bottom of the visualizer can look wrong on some browsers (e.g. on mobile), see

They should be implemented in a browser-independent way. Preferably with bootstrap elements, as that's a already a dependency.

### PR DESCRIPTION
**Pull request by SharanRP**
closes #2 

bootstrap components added 
image

### CODE REVIEW

**Comment by eimrek** [comment]
Hi @SharanRP. Thanks a lot for the contributions. sorry for the delays in checking your PRs, didn't really have the time in the past 2 weeks.

I checked this on chrome on ubuntu and there are still some problems:

image

I'll play around with css and try to fix it myself. Thanks!

**Comment by SharanRP** [comment]
@eimrek thank you for the reply, please do consider reviewing the remaining pull requests.

**Review by eimrek — APPROVED** [review]
Now it looks fine for me, merging.

In general, i am actually wondering if even using bootstrap was correct in this case, as it would either way require quite a bit of tweaking the css and in the end some parts are still different (e.g. no arrows on mobile in the supercell boxes). But I'll keep it like this for now.

Thanks!

**Comment by SharanRP** [comment]
Thank you

**Pull request merged**
